test

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -12,245 +12,255 @@ on:
     branches:
       - main
     tags:
-      - '**'
+      - 'v*-production'
+      - 'v*-stage'
   pull_request:
     branches:
-      - '**'
+      - main
 
 jobs:
-  npm:
+  set-environment:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-          cache: "npm"
-          cache-dependency-path: './wordpress/wp-content/themes/juicystrap/package-lock.json'
-
-      - name: Install dependencies
+      - name: Set Environment
+        id: set_env
         run: |
-          cd ./wordpress/wp-content/themes/juicystrap
-          rm -rf node_modules
-          npm install
+          echo ${github}
 
-  build-assets:
-    runs-on: ubuntu-latest
-    needs: npm
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-          cache: "npm"
-          cache-dependency-path: './wordpress/wp-content/themes/juicystrap/package-lock.json'
-
-      - name: Install dependencies
-        run: |
-          cd ./wordpress/wp-content/themes/juicystrap
-          npm install
-
-      - name: Build assets
-        run: |
-          cd ./wordpress/wp-content/themes/juicystrap
-          npm run production
-
-  prettier:
-    runs-on: ubuntu-latest
-    needs: npm
-    if: github.event.pull_request.draft == false || github.event.pull_request.draft == null
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-          cache: "npm"
-          cache-dependency-path: './wordpress/wp-content/themes/juicystrap/package-lock.json'
-
-      - name: Install dependencies
-        run: |
-          cd ./wordpress/wp-content/themes/juicystrap
-          npm install
-
-      - name: Run Prettier
-        run: |
-          cd ./wordpress/wp-content/themes/juicystrap
-          npm run lint:prettier
-
-  eslint:
-    runs-on: ubuntu-latest
-    needs: npm
-    if: github.event.pull_request.draft == false || github.event.pull_request.draft == null
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-          cache: "npm"
-          cache-dependency-path: './wordpress/wp-content/themes/juicystrap/package-lock.json'
-
-      - name: Install dependencies
-        run: |
-          cd ./wordpress/wp-content/themes/juicystrap
-          npm install
-
-      - name: Run ESLint
-        run: |
-          cd ./wordpress/wp-content/themes/juicystrap
-          npm run lint:js
-
-  stylelint:
-    runs-on: ubuntu-latest
-    needs: npm
-    if: github.event.pull_request.draft == false || github.event.pull_request.draft == null
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-          cache: "npm"
-          cache-dependency-path: './wordpress/wp-content/themes/juicystrap/package-lock.json'
-
-      - name: Install dependencies
-        run: |
-          cd ./wordpress/wp-content/themes/juicystrap
-          npm install
-
-      - name: Run StyleLint
-        run: |
-          cd ./wordpress/wp-content/themes/juicystrap
-          npm run lint:style
-
-  build-docker:
-    runs-on: ubuntu-latest
-    needs: [build-assets, prettier, eslint, stylelint]
-    if: startsWith(github.ref_name, 'v') && !contains(github.ref_name, ' ') && (endsWith(github.ref_name, '-stage') || endsWith(github.ref_name, '-production'))
-
-    permissions: write-all
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set environment variables
-        run: |
-          if [[ ${{ github.ref_name }} =~ ^v[^\s]+-production$ ]]; then
-            echo "ENVIRONMENT=production" >> $GITHUB_ENV
-          elif [[ ${{ github.ref_name }} =~ ^v[^\s]+-stage$ ]]; then
-            echo "ENVIRONMENT=stage" >> $GITHUB_ENV
-          else
-            echo "Undefined environment in tag"
-            echo "ENVIRONMENT=undefined" >> $GITHUB_ENV
-          fi
-
-          echo "TRIMMED_GITHUB_REF=$(echo "${{ github.ref_name }}" | cut -c2-)" >> $GITHUB_ENV
-
-      - name: Log in to the Container registry
-        uses: docker/login-action@v3
-        with:
-          registry: ${{ env.REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Extract metadata (tags, labels) for Docker
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}
-
-      - name: Build and push Docker image
-        run: |
-          docker build -t "${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TRIMMED_GITHUB_REF }}" -t "${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.ENVIRONMENT }}" .  --platform linux/amd64
-          if [ "${{ env.ENVIRONMENT }}" == "production" ]; then docker tag "${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TRIMMED_GITHUB_REF }}" "${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest"; fi
-          docker push --all-tags "${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}"
-
-      - name: Run Trivy vulnerability scanner
-        uses: aquasecurity/trivy-action@master
-        with:
-          image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}'
-          format: 'template'
-          exit-code: '0'
-          template: '@/contrib/sarif.tpl'
-          output: 'trivy-results.sarif'
-          severity: 'CRITICAL,HIGH'
-
-      - name: Upload Trivy scan results to GitHub Security tab
-        uses: github/codeql-action/upload-sarif@v3
-        with:
-          sarif_file: 'trivy-results.sarif'
-
-
-  deploy:
-    runs-on: ubuntu-latest
-    needs: build-docker
-    if: startsWith(github.ref_name, 'v') && !contains(github.ref_name, ' ') && (endsWith(github.ref_name, '-stage') || endsWith(github.ref_name, '-production'))
-
-    permissions:
-      id-token: write
-      contents: read
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: configure aws credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ secrets.ROLE_ARN }}
-          role-session-name: samplerolesession
-          aws-region: ${{ env.AWS_DEFAULT_REGION }}
-
-      - name: Deploy to AWS ECS
-        run: |
-          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment --no-cli-pager
-        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event_name != 'delete')
-
-  wait-for-deployment-to-complete:
-    runs-on: ubuntu-latest
-    needs: deploy
-    if: startsWith(github.ref_name, 'v') && !contains(github.ref_name, ' ') && (endsWith(github.ref_name, '-stage') || endsWith(github.ref_name, '-production'))
-
-    permissions:
-      id-token: write
-      contents: read
-
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
-
-    - name: Configure AWS credentials
-      uses: aws-actions/configure-aws-credentials@v4
-      with:
-        role-to-assume: ${{ secrets.ROLE_ARN }}
-        role-session-name: samplerolesession
-        aws-region: ${{ env.AWS_DEFAULT_REGION }}
-
-    - name: Verify identity
-      run: aws sts get-caller-identity
-
-    - name: Wait for ECS service to be stable (with retry)
-      env:
-        ECS_CLUSTER: ${{ env.ECS_CLUSTER }}
-        ECS_SERVICE: ${{ env.ECS_SERVICE }}
-      run: aws ecs wait services-stable --cluster $ECS_CLUSTER --service $ECS_SERVICE
-
-    - name: Check for previous step success
-      if: failure()
-      run: echo "ECS did not stabilize and therefore did NOT deploy."
-
-
+#  npm:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Set up Node.js
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: 20
+#          cache: "npm"
+#          cache-dependency-path: './wordpress/wp-content/themes/juicystrap/package-lock.json'
+#
+#      - name: Install dependencies
+#        run: |
+#          cd ./wordpress/wp-content/themes/juicystrap
+#          rm -rf node_modules
+#          npm install
+#
+#  build-assets:
+#    runs-on: ubuntu-latest
+#    needs: npm
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Set up Node.js
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: 20
+#          cache: "npm"
+#          cache-dependency-path: './wordpress/wp-content/themes/juicystrap/package-lock.json'
+#
+#      - name: Install dependencies
+#        run: |
+#          cd ./wordpress/wp-content/themes/juicystrap
+#          npm install
+#
+#      - name: Build assets
+#        run: |
+#          cd ./wordpress/wp-content/themes/juicystrap
+#          npm run production
+#
+#  prettier:
+#    runs-on: ubuntu-latest
+#    needs: npm
+#    if: github.event.pull_request.draft == false || github.event.pull_request.draft == null
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Set up Node.js
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: 20
+#          cache: "npm"
+#          cache-dependency-path: './wordpress/wp-content/themes/juicystrap/package-lock.json'
+#
+#      - name: Install dependencies
+#        run: |
+#          cd ./wordpress/wp-content/themes/juicystrap
+#          npm install
+#
+#      - name: Run Prettier
+#        run: |
+#          cd ./wordpress/wp-content/themes/juicystrap
+#          npm run lint:prettier
+#
+#  eslint:
+#    runs-on: ubuntu-latest
+#    needs: npm
+#    if: github.event.pull_request.draft == false || github.event.pull_request.draft == null
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Set up Node.js
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: 20
+#          cache: "npm"
+#          cache-dependency-path: './wordpress/wp-content/themes/juicystrap/package-lock.json'
+#
+#      - name: Install dependencies
+#        run: |
+#          cd ./wordpress/wp-content/themes/juicystrap
+#          npm install
+#
+#      - name: Run ESLint
+#        run: |
+#          cd ./wordpress/wp-content/themes/juicystrap
+#          npm run lint:js
+#
+#  stylelint:
+#    runs-on: ubuntu-latest
+#    needs: npm
+#    if: github.event.pull_request.draft == false || github.event.pull_request.draft == null
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Set up Node.js
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: 20
+#          cache: "npm"
+#          cache-dependency-path: './wordpress/wp-content/themes/juicystrap/package-lock.json'
+#
+#      - name: Install dependencies
+#        run: |
+#          cd ./wordpress/wp-content/themes/juicystrap
+#          npm install
+#
+#      - name: Run StyleLint
+#        run: |
+#          cd ./wordpress/wp-content/themes/juicystrap
+#          npm run lint:style
+#
+#  build-docker:
+#    runs-on: ubuntu-latest
+#    needs: [build-assets, prettier, eslint, stylelint]
+#    if: startsWith(github.ref_name, 'v') && !contains(github.ref_name, ' ') && (endsWith(github.ref_name, '-stage') || endsWith(github.ref_name, '-production'))
+#    environment: ${{ endsWith(github.ref_name, '-production') && 'production' || endsWith(github.ref_name, '-stage') && 'stage' }}
+#
+#    permissions: write-all
+#
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Set environment variables
+#        run: |
+#          if [[ ${{ github.ref_name }} =~ ^v[^\s]+-production$ ]]; then
+#            echo "ENVIRONMENT=production" >> $GITHUB_ENV
+#          elif [[ ${{ github.ref_name }} =~ ^v[^\s]+-stage$ ]]; then
+#            echo "ENVIRONMENT=stage" >> $GITHUB_ENV
+#          else
+#            echo "Undefined environment in tag"
+#            echo "ENVIRONMENT=undefined" >> $GITHUB_ENV
+#          fi
+#
+#          echo "TRIMMED_GITHUB_REF=$(echo "${{ github.ref_name }}" | cut -c2-)" >> $GITHUB_ENV
+#
+#      - name: Log in to the Container registry
+#        uses: docker/login-action@v3
+#        with:
+#          registry: ${{ env.REGISTRY }}
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Extract metadata (tags, labels) for Docker
+#        id: meta
+#        uses: docker/metadata-action@v5
+#        with:
+#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}
+#
+#      - name: Build and push Docker image
+#        run: |
+#          docker build -t "${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TRIMMED_GITHUB_REF }}" -t "${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.ENVIRONMENT }}" .  --platform linux/amd64
+#          if [ "${{ env.ENVIRONMENT }}" == "production" ]; then docker tag "${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TRIMMED_GITHUB_REF }}" "${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest"; fi
+#          docker push --all-tags "${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}"
+#
+#      - name: Run Trivy vulnerability scanner
+#        uses: aquasecurity/trivy-action@master
+#        with:
+#          image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}'
+#          format: 'template'
+#          exit-code: '0'
+#          template: '@/contrib/sarif.tpl'
+#          output: 'trivy-results.sarif'
+#          severity: 'CRITICAL,HIGH'
+#
+#      - name: Upload Trivy scan results to GitHub Security tab
+#        uses: github/codeql-action/upload-sarif@v3
+#        with:
+#          sarif_file: 'trivy-results.sarif'
+#
+#
+#  deploy:
+#    runs-on: ubuntu-latest
+#    needs: build-docker
+#    if: startsWith(github.ref_name, 'v') && !contains(github.ref_name, ' ') && (endsWith(github.ref_name, '-stage') || endsWith(github.ref_name, '-production'))
+#    environment: ${{ endsWith(github.ref_name, '-production') && 'production' || endsWith(github.ref_name, '-stage') && 'stage' }}
+#    permissions:
+#      id-token: write
+#      contents: read
+#
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: configure aws credentials
+#        uses: aws-actions/configure-aws-credentials@v4
+#        with:
+#          role-to-assume: ${{ secrets.ROLE_ARN }}
+#          role-session-name: samplerolesession
+#          aws-region: ${{ env.AWS_DEFAULT_REGION }}
+#
+#      - name: Deploy to AWS ECS
+#        run: |
+#          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment --no-cli-pager
+#        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event_name != 'delete')
+#
+#  wait-for-deployment-to-complete:
+#    runs-on: ubuntu-latest
+#    needs: deploy
+#    if: startsWith(github.ref_name, 'v') && !contains(github.ref_name, ' ') && (endsWith(github.ref_name, '-stage') || endsWith(github.ref_name, '-production'))
+#    environment: ${{ endsWith(github.ref_name, '-production') && 'production' || endsWith(github.ref_name, '-stage') && 'stage' }}
+#    permissions:
+#      id-token: write
+#      contents: read
+#
+#    steps:
+#    - name: Checkout repository
+#      uses: actions/checkout@v4
+#
+#    - name: Configure AWS credentials
+#      uses: aws-actions/configure-aws-credentials@v4
+#      with:
+#        role-to-assume: ${{ secrets.ROLE_ARN }}
+#        role-session-name: samplerolesession
+#        aws-region: ${{ env.AWS_DEFAULT_REGION }}
+#
+#    - name: Verify identity
+#      run: aws sts get-caller-identity
+#
+#    - name: Wait for ECS service to be stable (with retry)
+#      env:
+#        ECS_CLUSTER: ${{ env.ECS_CLUSTER }}
+#        ECS_SERVICE: ${{ env.ECS_SERVICE }}
+#      run: aws ecs wait services-stable --cluster $ECS_CLUSTER --service $ECS_SERVICE
+#
+#    - name: Check for previous step success
+#      if: failure()
+#      run: echo "ECS did not stabilize and therefore did NOT deploy."
+#
+#
